version = 0.1
[default.deploy.parameters]
stack_name = "task-management-app"
resolve_s3 = true
s3_prefix = "task-management-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
